---
title: "Chagas pathway"
author: "`r params$user_name`"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: html_document
params:
  user_name: 'NULL'
  num_scenarios: 'NULL'
  fig_diagram_scenarios1: 'NULL'
  values_box_scenarios1: 'NULL'
  prop_diagnosed_scenarios1: 'NULL' 
  cost_per_true_pos_scenarios1: 'NULL'
  plot_ppv_scenarios1: 'NULL'
  plot_npv_scenarios1: 'NULL'
  plot_cpc_scenarios1: 'NULL'
  table_res_scenarios1: 'NULL'
  fig_diagram_scenarios2: 'NULL'
  values_box_scenarios2: 'NULL'
  prop_diagnosed_scenarios2: 'NULL' 
  cost_per_true_pos_scenarios2: 'NULL'
  plot_ppv_scenarios2: 'NULL'
  plot_npv_scenarios2: 'NULL'
  plot_cpc_scenarios2: 'NULL'
  table_res_scenarios2: 'NULL'
  fig_diagram_scenarios3: 'NULL'
  prop_diagnosed_scenarios3: 'NULL' 
  cost_per_true_pos_scenarios3: 'NULL'
  values_box_scenarios3: 'NULL'
  plot_ppv_scenarios3: 'NULL'
  plot_npv_scenarios3: 'NULL'
  plot_cpc_scenarios3: 'NULL'
  table_res_scenarios3: 'NULL'
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=FALSE)

library(htmltools)


num_scenarios <- params$num_scenarios
  # sum(!is.null(params[["plot_ppv_scenarios1"]]), !is.null(params[["plot_ppv_scenarios2"]]), !is.null(params[["plot_ppv_scenarios3"]]))

#Calculate column class based on the number of scenarios
# if (num_scenarios == 1) {
#   column_class <- "col-md-12"
# } else if (num_scenarios == 2) {
#   column_class <- "col-md-6"
# } else {
#   column_class <- "col-md-4"
# }
```


<!-- <div class="row"> -->
```{r, results='asis', eval = num_scenarios >= 1}
cat('<div style="text-align: center;">') 
cat('<h3 style="font-weight: bold;">Scenario 1</h3>') 
cat("\n")
params[["fig_diagram_scenarios1"]]
params[["values_box_scenarios1"]]
params[["plot_ppv_scenarios1"]]
params[["plot_npv_scenarios1"]]
params[["plot_cpc_scenarios1"]]
params[["table_res_scenarios1"]]
cat("\n")
cat('</div>')
```

```{r, results='asis', eval = num_scenarios >= 2}
cat('<div style="text-align: center;">') 
cat('<h3 style="font-weight: bold;">Scenario 2</h3>')
cat("\n")
params[["fig_diagram_scenarios2"]]
params[["values_box_scenarios2"]]
params[["plot_ppv_scenarios2"]]
params[["plot_npv_scenarios2"]]
params[["plot_cpc_scenarios2"]]
params[["table_res_scenarios2"]]
cat("\n")
cat('</div>')
```

```{r, results='asis', eval = num_scenarios >= 3}
cat('<div style="text-align: center;">') 
cat('<h3 style="font-weight: bold;">Scenario 3</h3>')
cat("\n")
params[["fig_diagram_scenarios3"]]
params[["values_box_scenarios3"]]
params[["plot_ppv_scenarios3"]]
params[["plot_npv_scenarios3"]]
params[["plot_cpc_scenarios3"]]
params[["table_res_scenarios3"]]
cat("\n")
cat('</div>')
```

<!-- # ```{r, results='asis'} -->
<!-- # plotlist = list() -->
<!-- # if (num_scenarios >= 1) { -->
<!-- #   params[["fig_diagram_scenarios1"]] -->
<!-- #   params[["plot_ppv_scenarios1"]] -->
<!-- #  -->
<!-- # } -->

<!-- #Iterate over scenarios and generate columns -->
<!-- # res <- lapply(1:num_scenarios, function(i) params[[paste0("fig_diagram_scenarios", i)]]) -->
<!-- # res1 <- lapply(1:2, function(i) params[[paste0("plot_ppv_scenarios", i)]]) -->
<!-- # htmltools::tagList(res) -->
<!-- # htmltools::tagList(res1) -->

<!-- # for (i in 1:num_scenarios) { -->
<!-- #     scenario_name <- paste0("Scenario ", i) -->
<!-- #     # cat(paste0('<div class="', column_class, '">')) -->
<!-- #     # cat("\n", scenario_name, "\n") -->
<!-- #     # cat('<div style="text-align: center;">') -->
<!-- #     plotlist[[i]] <- list( -->
<!-- #         fig_diagra = params[[paste0("fig_diagram_scenarios", i)]], -->
<!-- #         plot_ppv = print(params[[paste0("plot_ppv_scenarios", i)]]) -->
<!-- #     ) -->
<!-- #     # print(params[[paste0("plot_ppv_scenarios", i)]]) -->
<!-- #     # print(params[[paste0("plot_npv_scenarios", i)]]) -->
<!-- #     # print(params[[paste0("plot_cpc_scenarios", i)]]) -->
<!-- #     # cat("</div>") -->
<!-- #     # cat("</div>") -->
<!-- #     # cat("\n") -->
<!-- # } -->
<!-- #  -->
<!-- # htmltools::tagList(setNames(plotlist, NULL)) -->
<!-- ``` -->
<!-- </div> -->



<!-- # ```{r, results='asis'} -->
<!-- # cat('<div style="text-align: center;">') -->
<!-- # print(params[["scatterplot_plot"]]) -->
<!-- # cat('</div>') -->
<!-- # -->
<!-- # # params[["scatterplot_plot"]] -->
<!-- # ``` -->


